### ISSUE TITLE
レポートのCSS・JSを読み込むパスを変動的にできるようにしたい

### ISSUE THREAD

**Issue by oganao** [epion-tropic-test-tool/epion-t3-rest#1]
Feature Kind（機能種別）

Choice Feature Kind（機能の種別を選んでください）

Command（単純な処理機能）

Please describe the Feature in detail.（機能について詳細に記載してください。）
coreの方で対応していただいたのと同様にrestのカスタムレポートについても
css,jsを読み込むパスを変動出来るようにしていただきたいです。

**Comment by takashno** [comment]
テンプレートおよびレポート機能にwebassetsパラメータの効果を伝搬するように修正
通常のレポートと同様に効果を出します。
